[package]
name = "coin_counter"
version = "0.1.0"
authors = ["Christopher Sardegna <gpg@reagentx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
num-format = "0.4.0"
